# Generated by Django 3.1.4 on 2021-02-13 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tweets", "0004_auto_20210205_1824"),
    ]

    operations = [
        migrations.AddField(
            model_name="tweet",
            name="parent",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tweets.tweet",
            ),
        ),
    ]
